[1337]
endpoint_url = "http://localhost:8545"

[1337.address]
funder = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
order_engine = "0x1b7754689d5bDf4618aA52dDD319D809a00B0843"
nft_c_0 = "0x312D098B64e32ef04736662249bd57AEfe053750"
nft_c_1 = "0xaa38b98b510781C6c726317FEb12610BEe90aE20"

[1337.uint]
nft_c_count = 2
final_week_Idx = 4
history_start_ts = 1765071695
history_end_ts = 1767490902
