[1337]
endpoint_url = "${ANVIL_RPC_URL}"

[1337.address]
funder = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
addr = "0x7C4B2f5D9E8A1c3E6F0A9bB4a2D1E5C8F9A6B7d2"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
dnft_erc721 = "0xf7461a489c71EAE6fA1Bfe69F8c3d661De0619Da"
verifying_contract = "0x87a97BC3a0EC7952F4F2C8d22eD5c0A56811fd10"
marketplace = "0x87a97BC3a0EC7952F4F2C8d22eD5c0A56811fd10"
