# ─────────────────────────────────────────────
# LOCAL FORK
# ─────────────────────────────────────────────
[1337]
endpoint_url = "${ANVIL_RPC_URL}"

[1337.address]
# nft contracts
bayc = "0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D"
mayc = "0x60E4d786628Fea6478F785A6d7e704777c86a7c6"
azuki = "0xED5AF388653567Af2F388E6224dC7C4b3241C544"
doodles = "0x8a90CAb2b38dba80c64b7734e58Ee1dB38B8992e"
meebits = "0x7Bd29408f11D2bFC23c34f18275bBf23bB716Bc7"
# ERC20s
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"

# (kept for reference, but don’t use in scripts yet)
crypto_punks_addr = "0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB"
