[1337]
endpoint_url = "${ANVIL_RPC_URL}"

[1337.address]
funder = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
addr = "0x7C4B2f5D9E8A1c3E6F0A9bB4a2D1E5C8F9A6B7d2"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
dmrktgremlin = "0x312D098B64e32ef04736662249bd57AEfe053750"
settlement_contract = "0x1b7754689d5bDf4618aA52dDD319D809a00B0843"
marketplace = "0x1b7754689d5bDf4618aA52dDD319D809a00B0843"
signature_verifier = "0x1b7754689d5bDf4618aA52dDD319D809a00B0843"
dmrktseal = "0xaa38b98b510781C6c726317FEb12610BEe90aE20"
