[1337]
endpoint_url = "${ANVIL_RPC_URL}"

[1337.address]
funder = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
addr = "0x7C4B2f5D9E8A1c3E6F0A9bB4a2D1E5C8F9A6B7d2"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
dnft_erc721 = "0xA75d83A22BaDdaFB38B78675Ea1535525E302502"
verifying_contract = "0xAF185e745b8d404c9cbC1a713D25d93f81c8672c"
marketplace = "0xAF185e745b8d404c9cbC1a713D25d93f81c8672c"
