[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "orderbook/=contracts/orderbook",
    "nfts/=contracts/nfts",
    "dev-script/=script/setup-dev",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts"
]

fs_permissions = [
    { access = "read", path = "./data/" },
    { access = "read-write", path = "deployments.toml" }
]

[rpc_endpoints]
fork = "http://localhost:8545"

[lint]
exclude_lints = ["unaliased-plain-import"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
